import type { Lead } from "@/lib/types";

export const leads: Lead[] = [
  {
    id: "1",
    name: "John Doe",
    phone: "+1 (817) 555-0123",
    status: "New",
    city: "Southlake",
    description: "Leaky faucet in kitchen",
    service: "General Repairs",
    serviceDetail: "Fixture refresh",
    scheduleWindow: "Wed · 10:00a - 12:00p",
    notificationEmail: "john.doe@example.com",
    documents: ["Estimate draft", "Site photos"],
    communications: ["Intake received", "Requested estimate window"],
    activeRequests: ["Confirm fixture brand", "Send under-sink photo"],
  },
  {
    id: "2",
    name: "Mary Johnson",
    phone: "+1 (817) 555-0456",
    status: "In Progress",
    city: "Keller",
    description: "Door frame repair and painting",
    service: "Carpentry",
    serviceDetail: "Trim + casing repair",
    scheduleWindow: "Thu · 2:00p - 4:00p",
    notificationEmail: "mary.johnson@example.com",
    documents: ["Scope confirmation", "Material list"],
    communications: ["Crew assigned", "Client confirmed paint code"],
    activeRequests: ["Collect paint code", "Approve casing profile"],
  },
  {
    id: "3",
    name: "Carlos Ramirez",
    phone: "+1 (682) 555-0789",
    status: "Completed",
    city: "Plano",
    description: "Outdoor light fixture replacement",
    service: "Outdoor Upkeep",
    serviceDetail: "Fixture refresh",
    scheduleWindow: "Mon · 9:00a - 11:00a",
    notificationEmail: "c.ramirez@example.com",
    documents: ["Final invoice", "Completion photos"],
    communications: ["Arrival confirmed", "Completion walkthrough"],
    activeRequests: ["Leave review", "Share warranty details"],
  },
];
